name: TrashBot
on:
  schedule:
    - cron: '0 * * * *'  # каждый час
  workflow_dispatch:
    inputs:
      mode:
        description: 'Режим запуска (normal/register/test)'
        required: false
        default: 'test'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          MODE: ${{ github.event.inputs.mode }}
      run: |
        MODE="${{ github.event.inputs.mode }}"
        if [ -z "$MODE" ]; then MODE=test; fi
        export MODE
        python bot.py