name: TrashBot
on:
  schedule:
    - cron: '*/15 * * * *'  # каждые 15 минут: окна 10:00, 20:00, 23:00
  workflow_dispatch:
    inputs:
      mode:
        description: 'Режим запуска (normal/register/test/maint_info/maint_purge/e2e)'
        required: false
        default: 'test'
      SCOPE:
        description: 'Группа получателей (testers/all)'
        required: false
        default: 'testers'

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          MODE: ${{ github.event.inputs.mode }}
          BOT_TZ: Europe/Moscow
          FIRE_TIMES: 10:00,20:00,23:00
          WINDOW_MIN: 15
          SCOPE: ${{ github.event.inputs.SCOPE }}
        run: |
          MODE="${{ github.event.inputs.mode }}"
          SCOPE="${{ github.event.inputs.SCOPE }}"
          if [ -z "$MODE" ]; then
            if [ "${{ github.event_name }}" = "schedule" ]; then MODE=normal; else MODE=test; fi
          fi
          if [ -z "$SCOPE" ]; then
            if [ "${{ github.event_name }}" = "schedule" ]; then SCOPE=all; else SCOPE=testers; fi
          fi
          export MODE
          export SCOPE
          python bot.py

      - name: Persist state
        if: ${{ always() && (github.event.inputs.mode != "test") }}
        run: |
          git config user.name "trashbot[bot]"
          git config user.email "trashbot-bot@users.noreply.github.com"
          git add state.json history.json e2e-result.json || true
          git commit -m "chore: update bot state [skip ci]" || true
          git push || true

      - name: Upload E2E result
        if: ${{ always() && (github.event.inputs.mode == "e2e") }}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-result
          path: e2e-result.json
          if-no-files-found: ignore
